### ISSUE TITLE
Log monitoring no longer functional in Chrome?

### ISSUE THREAD

**Issue by remd** [mapwatch/mapwatch#70] opened 2020-04-10 22:00 UTC
Hi. Earlier this week (maybe Monday or Tuesday evening?) Mapwatch stopped successfully monitoring the Client.txt file while Chrome is open.

I can refresh the site and upload my file again to get a new analysis but any live updates from Path of Exile are not recognized by Mapwatch.

I am using Google Chrome 81.0.4044.92 (Official Build) (64-bit).

Thank you for all of your work on this valuable tool.

**Comment by erosson** [comment] 2020-04-10 22:24
Confirmed after updating Chrome; looks like the [chrome bugfix](https://bugs.chromium.org/p/chromium/issues/detail?id=844874&q=component%3ABlink%3EFileAPI&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified) in #11/#51 was finally released. This Mapwatch functionality can't be fixed in Chrome or any other browser; damn.

I have a [downloadable version of Mapwatch](https://mapwatch.erosson.org/?downloadLink=1) built for when this happened. It's based on Chrome (Electron), and this update also broke it; oops. That's fixable though - will be ready soon.

Thanks for the report, and sorry for the inconvenience!

**Comment by erosson** [comment] 2020-04-10 23:03
[Only 1.6% of mapwatch's chrome users are on version 81](https://analytics.google.com/analytics/web/#/report/visitors-browser/a119582500w176920100p175689790/explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.browser:Chrome) - so this bug is still invisible for most folks, but will quickly become more visible as people upgrade

Aiming to fix the downloadable version later today

**Comment by erosson** [comment] 2020-04-11 02:47
[The downloadable version now updates while you play](https://github.com/mapwatch/mapwatch/releases/latest). Also, [wrote more about why browsers can't do this anymore](https://github.com/mapwatch/mapwatch/blob/master/WATCHING.md). 

That's about all I can do to fix this, so closing this issue. Please reopen/file a new issue if you have trouble with the Mapwatch download!

**Closed by erosson** 2020-04-11 02:47 UTC
Labels: bug
