### ISSUE TITLE
`nativefs` API release on Chromium browsers

### ISSUE THREAD

**Issue by TotomInc** [mapwatch/mapwatch#116] opened 2020-09-22 06:05 UTC
[Native filesystem API is available on the beta channel of Chromium-based browsers](https://caniuse.com/?search=native%20filesystem) according to caniuse.com.

The feature will be released soon but will take some time to propagate to the end-users (aka. let people update their web-browsers).

Maybe you will be able to implement it _again_ on the web-version? So we don't need to install third-party _Electron_ softwares (and they are very slow!).

**Comment by erosson** [comment] 2020-09-22 06:38
> Maybe you will be able to implement it again on the web-version?

Thanks - I already implemented a nativefs version, actually! Try it out: https://mapwatch.erosson.org/#?backend=www-nativefs

You'll see that it won't work. The problem is that nativefs has new rules about file locations: for example, `c:\program files` isn't allowed. PoE's log file usually isn't allowed. Of course, I can't ask GGG to change their log file path, or players to reinstall PoE at a new path. 

There's a workaround that I wrote about below that gets the nativefs version working - feel free to use it yourself! Sadly, it's too complex to make it the default for everyone; electron is unfortunately still the simplest option. 
https://github.com/mapwatch/mapwatch/blob/master/WATCHING.md#you-said-not-easily-available-in-any-web-browser-i-dont-want-to-downloadexecute-your-app-i-want-updates-while-i-play-and-i-have-some-technical-skills

**Comment by TotomInc** [comment] 2020-09-22 07:35
I hasn't really tried to mess with `nativefs` and didn't know it had strict rules (which was kinda obvious due to the nature of accessing native files from a browser).

Do you have a resource where you can find the security rules of the `nativefs` API (such as invalid files and folders)? I haven't been able ton find that.

Also I've tested mapwatch on the Chrome beta (v86.0.4240.42) but it doesn't work as you're using `window.chooseFileSystemEntries()` and it seems I only have `window.showOpenFilePicker()`.

Anyway, thanks for the update and sorry for the _useless_ issue.

**Comment by erosson** [comment] 2020-09-22 16:08
> Also I've tested mapwatch on the Chrome beta (v86.0.4240.42) but it doesn't work as you're using `window.chooseFileSystemEntries()` and it seems I only have `window.showOpenFilePicker()`.

Oh, they removed this in chrome beta? Huh - just tried it, and you're right. [This says both should work](https://wicg.github.io/native-file-system/#native-filesystem ), and both do work in production chrome (`Version 85.0.4183.102 (Official Build) (64-bit)`), but `showOpenFilePicker` is newer (didn't exist when I first implemented this) and there's no harm in switching to it.

I'll fix this before closing this issue, thanks for the report! I definitely want to support nativefs/browsers as much as possible, and wish it were possible to make it the default.

**Comment by erosson** [comment] 2020-09-22 19:29
This should work in chrome beta now! Can you verify it works for you before closing? https://mapwatch.erosson.org/#?backend=www-nativefs

You'll need to keep using `?backend=www-nativefs` to access mapwatch this way, unfortunately. Many people still use the website to see their map data without live updates, and I can't make all of them mess around with the hardlinks `nativefs` needs.

> Do you have a resource where you can find the security rules of the nativefs API (such as invalid files and folders)?

Nope, I never found this either. Only discovered the new rules after seeing my first implementation break. [The article I learned from mentions folder restrictions](https://web.dev/native-file-system/#restricted-folders), but no specifics.

**Comment by TotomInc** [comment] 2020-09-23 06:37
It seems to work fine now.

I installed PoE on another disk (`D:\Grinding Gear Games\Path of Exile\logs\Client.txt`) than my operating system (`C:\`) and the `nativefs` API haven't returned an error due to it being a "restricted folder".

![image](https://user-images.githubusercontent.com/9285210/93975460-c66a1d00-fd77-11ea-9b18-d2c3ab02011c.png)

It's also funny how the world is small, as I know you from the Swarm Simulator incremental-game that you made years ago! 🙂 

I think the issue can be closed now, as everything is working as _it should_.

**Comment by erosson** [comment] 2020-09-26 01:19
Excellent, thanks for verifying! 

> It's also funny how the world is small, as I know you from the Swarm Simulator incremental-game that you made years ago!

Ha - yes, that was me!

**Closed by erosson** 2020-09-26 01:19 UTC
Labels: bug
